### ISSUE TITLE
Calculate the popup position in the tower-select menu dependent of the image, not the click position

### ISSUE THREAD

**Issue by Mijago** [Apoc-/TowerDefense#10]
Currently, the position of the popup is calculated by the position to the click that triggered the popup to open. This is inconsistent, especially when opening the popup of two towers directly below each other, so the position should be calculated relative to the clicked tower image, not the click itself.
![image](https://user-images.githubusercontent.com/3903469/44169306-40794380-a0d4-11e8-93a1-02892981f9e1.png)

![image](https://user-images.githubusercontent.com/3903469/44169292-3a836280-a0d4-11e8-807a-0b38f13e43c9.png)

**Comment by Apoc-** [comment]
Could you please elaborate? I dont understand the problem.

**Comment by Mijago** [comment]
Keep track of the horizontal distance of the popup to the sidebar

![2018-08-15_22-11-54](https://user-images.githubusercontent.com/3903469/44170682-5b4db700-a0d8-11e8-9fc4-af07f2e253f8.gif)

**Comment by Apoc-** [comment]
Ahh, ok, Working as intended, just bad design 😸

**Comment by Apoc-** [comment]
Will not be worked on until the final zu is done.
