### ISSUE TITLE
Make Tower-Buttons in the UI scalable

### ISSUE THREAD

**Issue by Mijago** [Apoc-/TowerDefense#8]
Currently, when starting a game, the buttons to buy a tower do not scale but overlap each other on low resolutions.

![image](https://user-images.githubusercontent.com/3903469/44168819-c4cac700-a0d2-11e8-880b-b8d80acbec8c.png)

**Comment by Apoc-** [comment]
Should we support other resolutions?

Might be a lot of work doing this.

**Comment by Mijago** [comment]
From my point of view this is a really important feature. The Unity canvas should have the needed tools to make it less painful to implement this.

**Comment by Apoc-** [comment]
Will not be worked on until the final ui layout is done.
